service: fastify-backend

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${env:STAGE, 'prod'}
  region: ${env:AWS_DEFAULT_REGION, 'eu-west-3'}
  environment:
    NODE_ENV: lambda
    # DATABASE_URL: ${env:BACKEND_DATABASE_URL}
    JWT_SECRET: ${env:BACKEND_JWT_SECRET}
    API_BASE_URL: ${env:BACKEND_API_BASE_URL}

functions:
  app:
    handler: app/lambda.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000
